USER_FIELDS = ('id', 'age', 'gender', 'location')
TOPIC_IDS = ('crime_s1', 'crime_s2', 'crime_s3', 'econ_s1', 'econ_s2', 'econ_s3', 'edu_s1', 'edu_s2', 'edu_s3', 'env_s1', 'env_s2', 'env_s3', 'foreign_s1', 'foreign_s2', 'foreign_s3', 'heal_s1', 'heal_s2', 'heal_s3', 'imi_s1', 'imi_s2', 'imi_s3', 'ineq_s1', 'ineq_s2', 'ineq_s3', 'jobs_s1', 'jobs_s2', 'jobs_s3', 'living_s1', 'living_s2', 'living_s3', 'reform_s1', 'reform_s2', 'reform_s3', 'tax_s1', 'tax_s2', 'tax_s3', 'welfare_s1', 'welfare_s2', 'welfare_s3')
PRIORITY_IDS = ('priority_0', 'priority_1', 'priority_2', 'priority_3', 'priority_4', 'priority_5', 'priority_6', 'priority_7', 'priority_8', 'priority_9', 'priority_10', 'priority_11', 'priority_12', 'priority_13')
LOCATION_FIELDS = ('lat', 'lon', 'constituency_name', 'constituency_mapit_id')
# Calculated from the topics section of the bitetheballot.json, merging together
# older files with newer ones because some positions have been changed, and
# some statements added and deleted, but we need the whole lot here to match
# up against people's answers
PARTY_POSITIONS = {
    'crime_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'crime_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'crime_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'econ_s1': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'econ_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'econ_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'edu_s1': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 1,
        u'ukip': 0,
        },
    'edu_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'edu_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'env_s1': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'env_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'env_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 1,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'foreign_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'foreign_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'foreign_s3': {
        u'conservative': 1,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'heal_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'heal_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'heal_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0
        },
    'heal_s4': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'imi_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'imi_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'imi_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'imi_s4': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'ineq_s1': {
        u'conservative': 1,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'ineq_s2': {
        u'conservative': 1,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'ineq_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'ineq_s4': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'ineq_s5': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 1,
        'snp': 0,
        u'ukip': 0,
        },
    'jobs_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'jobs_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'jobs_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'living_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'living_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'living_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'reform_s1': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'reform_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 1,
        u'ukip': 1,
        },
    'reform_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 1,
        'snp': 0,
        u'ukip': 1,
        },
    'tax_s1': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'tax_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 0,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'tax_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 0,
        'snp': 1,
        u'ukip': 0,
        },
    'welfare_s1': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'welfare_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'welfare_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'welfare_s4': {
        u'conservative': 1,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 0,
        'snp': 1,
        u'ukip': 0,
        },
    }
# There are actually 44 topics, but this number is used in calculating the
# percentage scores for a given user, and represents the number of statements
# that were available to them when they answered the questions. In some topics
# newer statements have been added more recently, but older ones were removed
# to make room for them.
NUM_STATEMENTS = 39
VOTE_MATCH_FIELDS = ('user_id', 'living_conservative', 'living_labour', 'living_lib', 'living_ukip', 'living_green', 'living_snp', 'living_plcym', 'econ_conservative', 'econ_labour', 'econ_lib', 'econ_ukip', 'econ_green', 'econ_snp', 'econ_plcym', 'jobs_conservative', 'jobs_labour', 'jobs_lib', 'jobs_ukip', 'jobs_green', 'jobs_snp', 'jobs_plcym', 'reform_conservative', 'reform_labour', 'reform_lib', 'reform_ukip', 'reform_green', 'reform_snp', 'reform_plcym', 'imi_conservative', 'imi_labour', 'imi_lib', 'imi_ukip', 'imi_green', 'imi_snp', 'imi_plcym', 'heal_conservative', 'heal_labour', 'heal_lib', 'heal_ukip', 'heal_green', 'heal_snp', 'heal_plcym', 'welfare_conservative', 'welfare_labour', 'welfare_lib', 'welfare_ukip', 'welfare_green', 'welfare_snp', 'welfare_plcym', 'tax_conservative', 'tax_labour', 'tax_lib', 'tax_ukip', 'tax_green', 'tax_snp', 'tax_plcym', 'foreign_conservative', 'foreign_labour', 'foreign_lib', 'foreign_ukip', 'foreign_green', 'foreign_snp', 'foreign_plcym', 'env_conservative', 'env_labour', 'env_lib', 'env_ukip', 'env_green', 'env_snp', 'env_plcym', 'edu_conservative', 'edu_labour', 'edu_lib', 'edu_ukip', 'edu_green', 'edu_snp', 'edu_plcym', 'ineq_conservative', 'ineq_labour', 'ineq_lib', 'ineq_ukip', 'ineq_green', 'ineq_snp', 'ineq_plcym', 'crime_conservative', 'crime_labour', 'crime_lib', 'crime_ukip', 'crime_green', 'crime_snp', 'crime_plcym', 'conservative', 'labour', 'lib', 'ukip', 'green', 'snp', 'plcym')
