USER_FIELDS = ('id', 'age', 'gender', 'location')
TOPIC_IDS = ('crime_s1', 'crime_s2', 'crime_s3', 'econ_s1', 'econ_s2', 'econ_s3', 'edu_s1', 'edu_s2', 'edu_s3', 'env_s1', 'env_s2', 'env_s3', 'foreign_s1', 'foreign_s2', 'foreign_s3', 'heal_s1', 'heal_s2', 'heal_s3', 'imi_s1', 'imi_s2', 'imi_s3', 'ineq_s1', 'ineq_s2', 'ineq_s3', 'jobs_s1', 'jobs_s2', 'jobs_s3', 'living_s1', 'living_s2', 'living_s3', 'reform_s1', 'reform_s2', 'reform_s3', 'tax_s1', 'tax_s2', 'tax_s3', 'welfare_s1', 'welfare_s2', 'welfare_s3')
PRIORITY_IDS = ('priority_0', 'priority_1', 'priority_2', 'priority_3', 'priority_4', 'priority_5', 'priority_6', 'priority_7', 'priority_8', 'priority_9', 'priority_10', 'priority_11', 'priority_12', 'priority_13')
LOCATION_FIELDS = ('lat', 'lon', 'constituency_name', 'constituency_mapit_id')
# Calculated from the topics section of the bitetheballot.json, merging together
# older files with newer ones because some positions have been changed, and
# some statements added and deleted, but we need the whole lot here to match
# up against people's answers
PARTY_POSITIONS = {
    'crime_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'crime_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'crime_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'econ_s1': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'econ_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'econ_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'edu_s1': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 1,
        u'ukip': 0,
        },
    'edu_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'edu_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'env_s1': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'env_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'env_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 1,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'foreign_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'foreign_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'foreign_s3': {
        u'conservative': 1,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'heal_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'heal_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'heal_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0
        },
    'heal_s4': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'imi_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'imi_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'imi_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'imi_s4': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'ineq_s1': {
        u'conservative': 1,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'ineq_s2': {
        u'conservative': 1,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'ineq_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'ineq_s4': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'ineq_s5': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 1,
        'snp': 0,
        u'ukip': 0,
        },
    'jobs_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'jobs_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'jobs_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'living_s1': {
        u'conservative': 0,
        u'green': 0,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'living_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'living_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'reform_s1': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'reform_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 1,
        u'ukip': 1,
        },
    'reform_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 0,
        u'lib': 1,
        'plcym': 1,
        'snp': 0,
        u'ukip': 1,
        },
    'tax_s1': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'tax_s2': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 0,
        'plcym': 1,
        'snp': 1,
        u'ukip': 0,
        },
    'tax_s3': {
        u'conservative': 0,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 0,
        'snp': 1,
        u'ukip': 0,
        },
    'welfare_s1': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 1,
        },
    'welfare_s2': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 1,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'welfare_s3': {
        u'conservative': 1,
        u'green': 0,
        u'labour': 0,
        u'lib': 0,
        'plcym': 0,
        'snp': 0,
        u'ukip': 0,
        },
    'welfare_s4': {
        u'conservative': 1,
        u'green': 1,
        u'labour': 1,
        u'lib': 1,
        'plcym': 0,
        'snp': 1,
        u'ukip': 0,
        },
    }
